spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrdb
    username: pserviceuser
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hr-system
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8083
